name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: trades
    required: true
  - name: PRODUCT_IDS
    inputType: FreeText
    description: List of crypto currencies we want to get trades for
    defaultValue: '["ETH/USD", "BTC/USD"]'
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
