name: price_predictor
language: python
variables:
  - name: FEATURE_VIEW_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlcv_feature_view
    required: true
  - name: FEATURE_VIEW_VERSION
    inputType: FreeText
    description: ''
    defaultValue: 1
    required: true
  - name: OHLC_WINDOW_SEC
    inputType: FreeText
    description: ''
    defaultValue: 60
    required: true
  - name: FORECAST_STEPS
    inputType: FreeText
    description: ''
    defaultValue: 5
    required: true
  - name: ML_MODEL_STATUS
    inputType: FreeText
    description: ''
    defaultValue: production
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlcv_feature_group
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: ''
    defaultValue: 1
    required: true
dockerfile: Dockerfile
runEntryPoint: src/training.py
defaultFile: src/training.py
