name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: This is where trades are read from
    defaultValue: trade_live
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    description: this is where ohlcv candles are sent
    defaultValue: ohlcv_live
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: trades_to_ohlcv_consumer_group
    required: true
  - name: OHLCV_WINDOW_SECONDS
    inputType: FreeText
    description: window seconds
    defaultValue: '60 '
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
