name: Backfill Features

on:
  # for debugging purposes only. I will remove it before merging
  push:
    branches:
      - dev

  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  backfill_features_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quix CLI
        run: |
          echo Installing Quix CLI
          curl -fsSL https://github.com/quixio/quix-cli/raw/main/install.sh | bash

      - name: Login to Quix Cloud
        run: quix login ${{ secrets.QUIX_PAT }}

      - name: Backfill Features
        run: quix cloud deployments start ${{ secrets.DEV_BACKFILL_TRADE_PRODUCER_DEPLOYMENT_ID }}